# Generated by Django 2.2.5 on 2019-11-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20191029_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='starCount',
            field=models.IntegerField(null=True),
        ),
    ]
